
before_install:
   - "mysql -u root --password=\"dsmodoc\" < test/travis.sql"
install: true
jdk:
   - oraclejdk15
language: java
packages:
   - oracle-java8-installer
services:
   - mysql
script:
   - "mvn install"

